workflows:
  bootstrap_signing:
    name: Bootstrap signing (one-time)
    environment:
      xcode: 16.4
      groups:
        - appstore_connect
      vars:
        CERT_PASSWORD: "set-a-strong-password"   # временно, потом в Secrets
    scripts:
      - name: Generate key + CSR
        script: |
          set -euo pipefail
          openssl genrsa -out dist.key 2048
          # Укажи любой CN/email (не критично)
          openssl req -new -key dist.key -out dist.csr -subj "/CN=Apple Distribution/emailAddress=noreply@example.com"

      - name: Create Apple Distribution via API
        script: |
          set -euo pipefail
          # В разных версиях CLI синтаксис отличается. Попробуй по очереди:
          app-store-connect certificates create --type APPLE_DISTRIBUTION --csr-file dist.csr --output ios_distribution.cer || \
          app-store-connect certificates create --type IOS_DISTRIBUTION --csr-file dist.csr --output ios_distribution.cer

      - name: Make PKCS#12 (p12) and base64 for Secrets
        script: |
          set -euo pipefail
          openssl pkcs12 -export -inkey dist.key -in ios_distribution.cer -out dist.p12 -passout pass:"$CERT_PASSWORD"
          base64 dist.p12 > dist.p12.b64
    artifacts:
      - dist.p12.b64
