workflows:
  bootstrap_signing:
    name: Bootstrap signing (create iOS Distribution p12 once)
    max_build_duration: 10
    environment:
      xcode: 16.4
      groups:
        - appstore_connect   # APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY
      vars:
        CERT_PASSWORD: "set-strong-password-here"   # потом перенеси в Secrets
    scripts:
      - name: Generate private key
        script: |
          set -euo pipefail
          # создаём ключ без парольной фразы (проще для CI)
          openssl genrsa -out dist.key 2048

      - name: Create iOS Distribution cert via API and package into p12
        script: |
          set -euo pipefail
          # В твоей версии CLI нужен тип IOS_DISTRIBUTION и ключ, а не CSR
          app-store-connect certificates create \
            --type IOS_DISTRIBUTION \
            --certificate-key dist.key \
            --p12-password "$CERT_PASSWORD" \
            --p12-path dist.p12 \
            --save

      - name: Prepare artifact for Secrets (base64)
        script: |
          set -euo pipefail
          base64 dist.p12 > dist.p12.b64
    artifacts:
      - dist.p12.b64
