workflows:
  ios_appstore_autosign_grainflow:
    name: iOS App Store (Auto) – GrainFlow
    max_build_duration: 60

    environment:
      xcode: 16.4
      groups:
        - appstore_connect      # ISSUER_ID, KEY_IDENTIFIER, PRIVATE_KEY
        - signing               # CERT_P12 (+ CERT_PASSWORD если есть)
      vars:
        XCODE_PROJECT: "GrainFlow.xcodeproj"
        XCODE_WORKSPACE: "GrainFlow.xcworkspace"
        XCODE_SCHEME: "GrainFlow"
        BUNDLE_ID: "com.GrainFlow.hamzimdin"
        EXPORT_METHOD: "app-store"

    scripts:
      - name: Install dependencies (CocoaPods if present)
        script: |
          set -euo pipefail
          if [ -f "Podfile" ]; then
            gem install cocoapods --no-document
            pod install
            echo 'BUILD_TARGET=--workspace "GrainFlow.xcworkspace"' >> "$CM_ENV"
          else
            echo 'BUILD_TARGET=--project "GrainFlow.xcodeproj"' >> "$CM_ENV"
          fi

      - name: Bump build number (avoid duplicate CFBundleVersion)
        script: |
          set -euo pipefail
          agvtool new-version -all "$(date +%y%m%d%H%M)"

      - name: Import Distribution p12 into keychain
        script: |
          set -euo pipefail
          keychain initialize
          if [ -n "${CERT_P12:-}" ]; then
            echo "$CERT_P12" | base64 --decode > dist.p12
            if [ -n "${CERT_PASSWORD:-}" ]; then
              keychain add-certificates --certificate dist.p12 --certificate-password "$CERT_PASSWORD"
            else
              keychain add-certificates --certificate dist.p12
            fi
          else
            echo "No CERT_P12 provided; trying Codemagic identities..."
            keychain add-certificates || { echo "No certificate found. Add CERT_P12 secret or upload a p12 in Codemagic UI."; exit 1; }
          fi

          echo "== Code signing identities =="
          security find-identity -v -p codesigning || true

          # Принимаем оба названия: Apple Distribution / iPhone Distribution
          if ! security find-identity -v -p codesigning | grep -E -q "Apple Distribution|iPhone Distribution"; then
            echo "ERROR: Distribution identity not present"
            exit 1
          fi

      - name: Auto-provision profiles for the bundle id
        script: |
          set -euo pipefail
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create

      - name: Build IPA (Xcode automatic signing)
        script: |
          set -euo pipefail
          xcode-project build-ipa $BUILD_TARGET \
            --scheme "$XCODE_SCHEME" \
            --archive-flags="-destination 'generic/platform=iOS'" \
            --export-method "$EXPORT_METHOD" \
            --verbose

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/xcarchive/*.xcarchive
      - ~/Library/Logs/gym/*.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
