workflows:
  ios_appstore_autosign_grainflow:
    name: iOS App Store – GrainFlow
    max_build_duration: 60

    environment:
      xcode: 16.4
      groups:
        - appstore_connect
        - signing
      vars:
        XCODE_SCHEME: "GrainFlow"
        BUNDLE_ID: "com.GrainFlow.hamzimdin"
        EXPORT_METHOD: "app-store"

    scripts:
      - name: Install dependencies
        script: |
          set -euo pipefail
          if [ -f "Podfile" ]; then
            echo "Installing CocoaPods dependencies..."
            gem install cocoapods --no-document
            pod install
            echo "Using workspace for build"
          else
            echo "Using project for build"
          fi

      - name: Bump build number
        script: |
          set -euo pipefail
          agvtool new-version -all "$(date +%y%m%d%H%M)"

      - name: Import Distribution p12 into keychain
        script: |
          set -euo pipefail
          keychain initialize
          echo "$CERT_P12" | base64 --decode > dist.p12
          if [ -n "${CERT_PASSWORD:-}" ]; then
            keychain add-certificates --certificate dist.p12 --certificate-password "$CERT_PASSWORD"
          else
            keychain add-certificates --certificate dist.p12
          fi
          echo "== Code signing identities =="
          security find-identity -v -p codesigning
          security find-identity -v -p codesigning | grep -E -q "Apple Distribution|iPhone Distribution" \
            || { echo "ERROR: distribution identity not found in keychain"; exit 1; }

      - name: Build and export .ipa
        script: |
          set -euo pipefail
          
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          
          # Определяем тип проекта
          if [ -f "Podfile" ] && [ -d "GrainFlow.xcworkspace" ]; then
            echo "Building with workspace..."
            xcode-project build-archive \
              --workspace "GrainFlow.xcworkspace" \
              --scheme "$XCODE_SCHEME" \
              --output "build/GrainFlow.xcarchive"
          elif [ -d "GrainFlow.xcodeproj" ]; then
            echo "Building with project..."
            xcode-project build-archive \
              --project "GrainFlow.xcodeproj" \
              --scheme "$XCODE_SCHEME" \
              --output "build/GrainFlow.xcarchive"
          else
            echo "ERROR: No project or workspace found!"
            echo "Available files:"
            find . -name "*.xcodeproj" -o -name "*.xcworkspace" | head -10
            exit 1
          fi
          
          # Экспорт IPA
          xcode-project export-archive \
            --archive-path "build/GrainFlow.xcarchive" \
            --output "build" \
            --export-method "$EXPORT_METHOD"

      - name: Deploy to App Store Connect
        script: |
          set -euo pipefail
          IPA_PATH=$(find "build" -name "*.ipa" | head -1)
          if [ -z "$IPA_PATH" ]; then
            echo "No .ipa file found!"
            echo "Build directory contents:"
            find "build" -type f
            exit 1
          fi
          echo "Found IPA: $IPA_PATH"
          app-store-connect upload "$IPA_PATH"
